import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { GoogleGenAI, Type } from "@google/genai";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "20mb" }));

// Helper to instantiate Gemini SDK lazily
function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return null;
  return new GoogleGenAI({
    apiKey: apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// Pre-seeded company document repository for RAG simulation
const COMPANY_KNOWLEDGE_BASE: Record<string, { title: string; type: string; content: string }> = {
  "doc-1": {
    title: "SmartBiz Employee Handbook & Support SLA 2026.pdf",
    type: "PDF",
    content: `
SmartBiz AI Customer Support & Operational Guidelines:
1. Standard Support SLA: Response time for Pro customers is within 2 hours. Response time for Enterprise customers is within 15 minutes with 24/7 dedicated telephone line.
2. Return & Refund Policy: Customers are eligible for a full 14-day money-back guarantee on initial subscriptions. Unused AI credits automatically roll over up to 60 days.
3. Escalation Matrix: Level 1 handles billing and general AI content queries. Level 2 technical team manages API integrations and custom model fine-tuning. Level 3 DevOps handles data sovereignty and dedicated instance deployments.
4. Security Standards: All customer document uploads are encrypted at rest with AES-256 and in transit via TLS 1.3. Documents are NEVER used to train shared public models.
`,
  },
  "doc-2": {
    title: "SmartBiz Enterprise Pricing & SLA Matrix.docx",
    type: "DOCX",
    content: `
SmartBiz AI Subscription Tier Overview:
- Starter / Free Tier ($0/mo): Includes 100 AI credits/mo, 1 user seat, document Q&A up to 5MB, basic email summarizer.
- Pro Automation Plan ($49/mo): Includes 5,000 AI credits/mo, 5 user seats, Unlimited Document OCR, AI Content Suite, Custom Brand Voice, priority support.
- Enterprise Custom ($199/mo): Includes 50,000 AI credits/mo, Unlimited seats, Custom Fine-Tuned RAG, Dedicated Database tenant, SLA uptime guarantee 99.95%, custom Stripe billing integration, API access.
- Add-on Credits: $15 per 2,500 extra AI tokens.
`,
  },
  "doc-3": {
    title: "Q2 Sales & Product Strategy Highlights.txt",
    type: "TXT",
    content: `
SmartBiz Q2 Performance & Roadmap:
- Gross Revenue growth: +34% YoY with 420 active SaaS business accounts.
- Churn Rate reduced to 1.8% due to automated document OCR and email drafting workflows.
- Top converting marketing channel: LinkedIn Video Ads and Cold Email Outbound campaigns generated by SmartBiz Content Generator.
- Key product priorities for Q3: Expanded multi-language translation (12 languages), automated invoice export to QuickBooks and Xero, automated Slack support bot.
`,
  },
};

// --- API ENDPOINTS ---

// Health Check
app.get("/api/health", (req, res) => {
  const hasKey = !!process.env.GEMINI_API_KEY;
  res.json({
    status: "ok",
    aiConfigured: hasKey,
    timestamp: new Date().toISOString(),
  });
});

// 1. RAG Document Chatbot API
app.post("/api/chat/document", async (req, res) => {
  try {
    const { prompt, documentIds, customDocContent, history = [] } = req.body;
    const ai = getGeminiClient();

    // Gather context from selected documents or custom uploads
    let context = "";
    const citations: string[] = [];

    if (customDocContent) {
      context += `[Uploaded Custom Document]\n${customDocContent}\n\n`;
      citations.push("User Uploaded Document");
    }

    if (Array.isArray(documentIds) && documentIds.length > 0) {
      documentIds.forEach((id: string) => {
        if (COMPANY_KNOWLEDGE_BASE[id]) {
          const doc = COMPANY_KNOWLEDGE_BASE[id];
          context += `[Document: ${doc.title}]\n${doc.content}\n\n`;
          citations.push(doc.title);
        }
      });
    } else if (!customDocContent) {
      // Default to all docs if none specified
      Object.values(COMPANY_KNOWLEDGE_BASE).forEach((doc) => {
        context += `[Document: ${doc.title}]\n${doc.content}\n\n`;
        citations.push(doc.title);
      });
    }

    if (ai) {
      const systemInstruction = `You are SmartBiz AI, an elite enterprise knowledge assistant trained on company files.
You answer user questions strictly based on the provided company document context.
If the answer is found in the documents, state it clearly, cite the document name, and highlight key takeaways.
If the information is not explicitly covered, provide a professional response while indicating it is based on general business standard practice.
Keep responses concise, formatted with clear headings, bullet points, and actionable steps.`;

      const promptText = `COMPANY DOCUMENT CONTEXT:\n${context}\n\nUSER QUESTION: ${prompt}`;

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: promptText,
        config: {
          systemInstruction,
          temperature: 0.3,
        },
      });

      res.json({
        answer: response.text || "No response generated.",
        citations: Array.from(new Set(citations)),
        confidenceScore: 0.96,
        suggestedFollowups: [
          "How does this policy apply to Pro subscribers?",
          "Can you summarize the key escalation steps?",
          "What is the refund window for annual plans?",
        ],
      });
    } else {
      // Smart fallback when key is not provided
      res.json({
        answer: `Based on **SmartBiz Company Documents**:\n\n• **SLA Guarantee**: Enterprise clients receive responses within 15 minutes, while Pro users enjoy a 2-hour guarantee.\n• **Subscriptions**: Starter ($0/mo), Pro ($49/mo), and Enterprise ($199/mo) offer flexible token tiers.\n• **Data Security**: Documents are protected with AES-256 encryption and TLS 1.3 in transit.\n\n*Source Docs Referenced*: ${citations.join(", ")}`,
        citations: Array.from(new Set(citations)),
        confidenceScore: 0.94,
        suggestedFollowups: [
          "What is the return policy duration?",
          "How many user seats are in the Pro plan?",
          "Are credits rolled over month-to-month?",
        ],
      });
    }
  } catch (err: any) {
    console.error("Document Chat Error:", err);
    res.status(500).json({ error: err.message || "Failed to query documents." });
  }
});

// 2. AI Content Generator API
app.post("/api/content/generate", async (req, res) => {
  try {
    const { contentType, topic, tone = "Professional", targetAudience = "Business Owners", language = "English", keyPoints = "" } = req.body;
    const ai = getGeminiClient();

    if (ai) {
      const prompt = `Generate high-converting marketing content in ${language}.
Content Type: ${contentType} (e.g., Blog Post, LinkedIn Post, Ad Copy, Sales Cold Email)
Topic / Product: ${topic}
Tone of Voice: ${tone}
Target Audience: ${targetAudience}
Key Highlights / USPs: ${keyPoints}

Structure the response neatly with:
1. Title / Headline Options (3 catchy variations)
2. Primary Copy Content (Rich Markdown with emojis, clear paragraphs, call-to-actions)
3. Hashtags or Search Keywords
4. Estimated Read Time / Engagement Score Prediction`;

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an expert SaaS copywriter and growth marketer.",
          temperature: 0.7,
        },
      });

      res.json({
        content: response.text,
        wordCount: response.text?.split(/\s+/).length || 240,
        estimatedEngagement: "High (92/100)",
        language,
      });
    } else {
      res.json({
        content: `### 🚀 Title: Automate Your Workflow with ${topic}

Are you spending hours managing manual processes? **${topic}** is engineered specifically for ${targetAudience} to eliminate bottlenecks and accelerate revenue.

#### Key Advantages:
${keyPoints ? keyPoints.split('\n').map(pt => `• ${pt}`).join('\n') : '• Save 15+ hours per week\n• AI-driven automated insights\n• Seamless enterprise team collaboration'}

#### Call to Action:
👉 **Try SmartBiz AI free for 14 days and scale your operations effortlessly.**

#BusinessAutomation #${contentType.replace(/\s+/g, '')} #SaaS #Productivity`,
        wordCount: 180,
        estimatedEngagement: "High (89/100)",
        language,
      });
    }
  } catch (err: any) {
    console.error("Content Generation Error:", err);
    res.status(500).json({ error: err.message || "Failed to generate content." });
  }
});

// 3. Invoice OCR & Data Extraction API
app.post("/api/ocr/invoice", async (req, res) => {
  try {
    const { imageBase64, invoiceText, sampleId } = req.body;
    const ai = getGeminiClient();

    if (ai && (imageBase64 || invoiceText)) {
      const systemInstruction = `Extract structured invoice or receipt data into strict JSON matching the schema provided.
Do not include extra commentary, only valid JSON.`;

      let contentsParts: any[] = [];
      if (imageBase64) {
        // Strip data prefix if present
        const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, "");
        contentsParts.push({
          inlineData: {
            mimeType: "image/png",
            data: cleanBase64,
          },
        });
        contentsParts.push({ text: "Extract all invoice attributes: vendor, invoiceNo, date, currency, lineItems, subtotal, tax, total, expenseCategory, paymentStatus." });
      } else {
        contentsParts.push({ text: `Extract all invoice data from this text:\n${invoiceText}` });
      }

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: { parts: contentsParts },
        config: {
          systemInstruction,
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              vendorName: { type: Type.STRING },
              invoiceNumber: { type: Type.STRING },
              date: { type: Type.STRING },
              dueDate: { type: Type.STRING },
              currency: { type: Type.STRING },
              lineItems: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    description: { type: Type.STRING },
                    quantity: { type: Type.NUMBER },
                    unitPrice: { type: Type.NUMBER },
                    amount: { type: Type.NUMBER },
                  },
                },
              },
              subtotal: { type: Type.NUMBER },
              tax: { type: Type.NUMBER },
              totalAmount: { type: Type.NUMBER },
              category: { type: Type.STRING },
              paymentStatus: { type: Type.STRING },
              confidenceScore: { type: Type.NUMBER },
            },
          },
        },
      });

      const parsed = JSON.parse(response.text || "{}");
      res.json(parsed);
    } else {
      // Mock / Sample responses for seamless demonstration
      const sampleInvoices: Record<string, any> = {
        aws: {
          vendorName: "Amazon Web Services Inc.",
          invoiceNumber: "INV-2026-88910",
          date: "2026-07-28",
          dueDate: "2026-08-15",
          currency: "USD",
          lineItems: [
            { description: "Cloud Run Container Hosting (Standard)", quantity: 1, unitPrice: 240.0, amount: 240.0 },
            { description: "Cloud Storage Bucket Assets", quantity: 50, unitPrice: 0.8, amount: 40.0 },
            { description: "Managed Egress Data Transfer", quantity: 1, unitPrice: 35.5, amount: 35.5 },
          ],
          subtotal: 315.5,
          tax: 28.39,
          totalAmount: 343.89,
          category: "Cloud Infrastructure",
          paymentStatus: "Paid",
          confidenceScore: 0.99,
        },
        office: {
          vendorName: "Staples Business Center",
          invoiceNumber: "ST-449102",
          date: "2026-07-20",
          dueDate: "2026-07-20",
          currency: "USD",
          lineItems: [
            { description: "Ergonomic Mesh Desk Chairs", quantity: 2, unitPrice: 189.99, amount: 379.98 },
            { description: "Dual Monitor Stand Arm", quantity: 2, unitPrice: 45.0, amount: 90.0 },
            { description: "Recycled Paper Reams (Box of 5)", quantity: 3, unitPrice: 22.0, amount: 66.0 },
          ],
          subtotal: 535.98,
          tax: 42.88,
          totalAmount: 578.86,
          category: "Office Equipment",
          paymentStatus: "Paid",
          confidenceScore: 0.97,
        },
        software: {
          vendorName: "Figma Inc.",
          invoiceNumber: "FIG-882319",
          date: "2026-07-01",
          dueDate: "2026-07-01",
          currency: "USD",
          lineItems: [
            { description: "Figma Organization Plan - Annual Seats", quantity: 8, unitPrice: 45.0, amount: 360.0 },
            { description: "FigJam Team Add-on", quantity: 8, unitPrice: 12.0, amount: 96.0 },
          ],
          subtotal: 456.0,
          tax: 36.48,
          totalAmount: 492.48,
          category: "Software Subscription",
          paymentStatus: "Approved",
          confidenceScore: 0.98,
        },
      };

      const selected = sampleInvoices[sampleId] || sampleInvoices["aws"];
      res.json(selected);
    }
  } catch (err: any) {
    console.error("Invoice OCR Error:", err);
    res.status(500).json({ error: err.message || "Failed to parse invoice." });
  }
});

// 4. Sales Report & Business Analytics AI API
app.post("/api/analytics/insights", async (req, res) => {
  try {
    const { timeframe = "Q2 2026", metrics } = req.body;
    const ai = getGeminiClient();

    if (ai) {
      const prompt = `Perform executive AI analysis on the following company performance metrics for ${timeframe}:
${JSON.stringify(metrics || { grossRevenue: 142000, mrrGrowth: 18.4, churnRate: 1.2, topProduct: "Pro Automation", CustomerAcquisitionCost: 85 })}

Provide a concise, high-impact business analysis report with:
1. Executive Summary
2. Top Growth Drivers
3. Risk Flags & Anomalies
4. Actionable Next Steps (3 strategic recommendations)`;

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a Chief Financial Officer and Business Intelligence AI Advisor.",
        },
      });

      res.json({
        executiveSummary: response.text,
        generatedAt: new Date().toISOString(),
        score: "A+",
      });
    } else {
      res.json({
        executiveSummary: `### 📊 Executive AI Performance Report (${timeframe})

#### Key Highlights:
• **Revenue Growth**: Gross Revenue hit **$142,500** (+18.4% MRR expansion), driven primarily by Enterprise plan upgrades.
• **Efficiency Ratio**: Customer Acquisition Cost (CAC) dropped to **$85**, yielding a healthy **4.2x LTV:CAC ratio**.
• **Retention**: Monthly subscriber churn is at an all-time low of **1.2%**.

#### 🎯 Strategic Recommendations:
1. **Expand AI Document Credits**: 34% of active Pro teams are approaching their monthly credit limit. Introducing automatic top-ups could boost MRR by +8%.
2. **Optimize Content Generator**: Blog copy generation accounts for 45% of total API usage. Promote annual billing incentives.
3. **Automate Invoice Syncing**: Integrating direct QuickBooks exporting will unlock the accounting vertical.`,
        generatedAt: new Date().toISOString(),
        score: "A+",
      });
    }
  } catch (err: any) {
    console.error("Analytics Insights Error:", err);
    res.status(500).json({ error: err.message || "Failed to generate business analytics." });
  }
});

// 5. AI Email Writer & Summarizer API
app.post("/api/email/process", async (req, res) => {
  try {
    const { action = "summarize", emailText, customInstruction = "" } = req.body;
    const ai = getGeminiClient();

    if (ai) {
      const prompt = action === "summarize"
        ? `Analyze this business email thread. Provide:
1. Concise 3-bullet summary
2. Detected Sentiment (Positive, Neutral, Urgent/Frustrated)
3. Key Customer Action Items requested

EMAIL THREAD:
${emailText}`
        : `Draft 3 professional email responses to the following email thread based on instructions "${customInstruction}".
Variant 1: Direct & Solution-Focused
Variant 2: Warm & Apologetic / Empathetic
Variant 3: Executive & Upsell opportunity

EMAIL THREAD:
${emailText}`;

      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an elite customer communication assistant.",
        },
      });

      res.json({
        result: response.text,
        action,
      });
    } else {
      if (action === "summarize") {
        res.json({
          result: `### ✉️ Email Summary
• **Core Request**: Client requests urgent assistance with integrating SmartBiz AI OCR into their existing QuickBooks workflow.
• **Sentiment**: ⚡ Urgent / High Interest
• **Action Required**: Needs API key permission update and confirmation of custom webhook delivery schedule by Friday.`,
          action,
        });
      } else {
        res.json({
          result: `### ✉️ Generated Smart Replies

#### Option 1: Direct & Solution-Focused
> Hi Sarah,
> 
> Thank you for reaching out! We can absolutely enable QuickBooks OCR webhook integration for your organization. I have enabled the API scope on your account and attached our setup guide. Let's schedule a 10-minute call if you need developer assistance.
> 
> Best regards,
> Alex | SmartBiz AI Team

#### Option 2: Executive & Partnership Expansion
> Dear Sarah,
> 
> I appreciate your email. Our team has prioritized your request, and your account manager is ready to configure your dedicated webhook queue. As part of your Enterprise plan, this feature includes zero-downtime SLA.
> 
> Warmly,
> Alex`,
          action,
        });
      }
    }
  } catch (err: any) {
    console.error("Email API Error:", err);
    res.status(500).json({ error: err.message || "Failed to process email." });
  }
});

// Serve frontend with Vite middleware in dev or static files in production
async function setupServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`SmartBiz AI Fullstack Server running on http://0.0.0.0:${PORT}`);
  });
}

setupServer();
